baseURL: https://sylvia-hu.netlify.app/
languageCode: en-us
title: Portfolio website for Sylvia Hu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      MFA2022 student at London Business School.
    title: Hi, my name is Sylvia Hu
  blog: {}
  contact:
    address:
      - city: London
        country: United Kingdom
        street: Regent's Park, NW14SAL
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: shu.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (+44) 077-5294-1536
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Sylvia Hu
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://www.twitter.com/SylviaHu08
      - icon: fa-facebook
        label: Facebook
        url: https://www.facebook.com/xingyu.hu.35
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/sylvia_xyhu
      - icon: fa-github
        label: GitHub
        url: https://www.github.com/Sylvia199808
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/xingyu-hu-sylvia
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: '#'
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Biography
        url: blogs/About_Sylvia
      - name: R Analysis
        url: blogs/PJ
      - name: Essay
        url: /img/blogs/song_at_sunset.pdf
      - name: Photo Album
        url: blogs/sunset
    menu: Menu
    subtitle: Portfolio Website
    title: Sylvia Hu
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
        subtitle: Biography
        title: About me
        url: blogs/About_Sylvia
      - image: stock01.jpg
        subtitle: DJIA performance
        title: Risk Return of DJIA Industrial Average
        url: blogs/PJ/risk_return
      - image: rating.jpg
        subtitle: Difference for Spielberg and Tim Burton
        title: Mean IMDB Ratings
        url: blogs/PJ/directors
      - image: gdp01.jpg
        subtitle: Comparison among France, China and United States
        title: GDP components over time and among countries
        url: blogs/PJ/GDP
      - image: whitman.jpg
        subtitle: Analysis of a Whitman's Poem
        title: Broad Love For Nature America And People
        url: /img/blogs/song_at_sunset.pdf
      - image: la.jpg
        subtitle: Photo Album of Sunset
        title: Sunset at California
        url: blogs/sunset
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Thanks for visiting my website.
    \r\n I love to make friends and would like to share more with you.
    \r\n If you are interested, please find my social media accounts down below and get connected!"
    title: Get Connected
    url: '#'
  
